name: Release

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(join(github.event.pull_request.labels.*.name), 'skip-release') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@6rawn"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run release
